# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 877a692dc22534a7e67d0defbe2e38aa278a47e0f4c6d0768454ba76e032b3123c8df9a2d7966ffa65719203014aa97b87406a86d3fd6ac734eca6cd9d7a2d92

test:
  secret_key_base: f547be9d527a1c29f954a92d9073f0c22a4ff1eafd21a8d000806b3c50b96ec9f698dbf51921d9483b9b495e0771e5c988dd2da0258c014f2011226926bcb484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
